Added headings in the client/lxd_instances.go file that were missing
canonical/lxd pull request #11924
Opened 2023-07-04 11:27 UTC by ibilalkayy

Hey there,

I just added headings in the **client/lxd_instances.go** file that were missing. With these headings, it will be easy to understand what these functions do.

Thank you!

2023-07-04 11:28 UTC, tomponline commented
Hi @ibilalkayy I wonder is it possible for you to submit multiple commits for these changes inside a single PR rather than opening lots of PR. This way we can review and test the changes in one shot. Thanks

2023-07-04 11:34 UTC, ibilalkayy commented
@tomponline  Alright. I will send one PR. Thank you, for letting me know!

2023-07-04 14:24 UTC, tomponline commented on client/lxd_instances.go
> +// tryCreateInstance attempts to create a new instance on multiple target servers specified by their URLs.
Please can you split the last 2 comments into their own commit to aid backporting.

2023-07-04 14:24 UTC, tomponline requested changes
We need to split these changes up so that last 2 comments can be backported.

2023-07-05 11:32 UTC, ibilalkayy commented
In **lxd_instances.go** file, I added 4 headings above the 4 functions. Should I split these comments into 4 commits?

2023-07-05 12:52 UTC, ibilalkayy commented
I splitted 4 comments into 4 commits.

2023-07-06 08:14 UTC, tomponline approved these changes
Thanks!

2023-07-06 08:14 UTC, merged