Cluster: Remove obsolete group delete/create for post
canonical/lxd pull request #11946
Opened 2023-07-05 15:45 UTC by roosterfish

The `nodes_cluster_groups` table doesn't have a row with the given group_id if the group itself doesn't have any members. This leads to the error message `NodeClusterGroup not found` when trying to delete all rows affecting the cluster group.

Since the list of active and required members already gets compared and created/removed by another loop, this deletion/creation is effectively not required.

2023-07-05 15:47 UTC, tomponline requested changes
Please can we have a test added for this?

Does the `lxc` CLI use the PUT?

2023-07-05 15:51 UTC, roosterfish commented
> Does the `lxc` CLI use the PUT?

When you do `lxc cluster group edit {name}`.

2023-07-06 07:55 UTC, tomponline approved these changes

2023-07-06 07:55 UTC, merged

2023-07-06 07:56 UTC, monstermunchkin approved these changes
Your change looks fine. I couldn't figure out why the code was added in the first place (it was added here btw:  d098c1afd3bf8baf765618ef889d6874c4a078b3). Also, the loop will never run as `obj.Nodes` should in theory always be empty. So, removing this section seems to make sense to me.

@masnax wdyt?