Fix/set attributes cmd
canonical/lxd pull request #11961
Opened 2023-07-07 10:12 UTC by gabrielmougard

closes #10960

2023-07-07 14:00 UTC, monstermunchkin commented
@gabrielmougard could you please add some tests?

2023-07-07 14:26 UTC, monstermunchkin requested changes

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/cluster.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an cluster attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a cluster attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/cluster.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as an cluster attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as a cluster attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network.go
> +	}
```suggestion
	c.networkSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_acl.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an network ACL attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a network ACL attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_acl.go
> +	}
```suggestion
	c.networkACLSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_forward.go
> +			return fmt.Errorf(i18n.G("The attribute %q does not exist on network forwardd %q"), args[2], resource.name)
```suggestion
			return fmt.Errorf(i18n.G("The attribute %q does not exist on network forward %q"), args[2], resource.name)
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_forward.go
> +	}
```suggestion
	c.networkForwardSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_load_balancer.go
> +	}
```suggestion
	c.networkLoadBalancerSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_peer.go
> +	}
```suggestion
	c.networkPeerSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_zone.go
> +	}
```suggestion
	c.networkZoneSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/network_zone.go
> +	}
```suggestion
	c.networkZoneRecordSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/profile.go
> +	}
```suggestion
	c.profileSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/project.go
> +	}
```suggestion
	c.projectSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/storage.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as a storage attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Unset the key as a storage attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/storage.go
> +	}
```suggestion
	c.storageSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/storage_bucket.go
> +	}
```suggestion
	c.storageBucketSet.flagIsAttribute = if c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/storage_volume.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Get the key as an instance attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as a storage volume attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/storage_volume.go
> +	}
```suggestion
	c.storageVolumeSet.flagIsAttribute = c.flagIsAttribute
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/cluster.go
> +	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as an instance attribute"))
```suggestion
	cmd.Flags().BoolVarP(&c.flagIsAttribute, "attribute", "a", false, i18n.G("Set the key as a cluster attribute"))
```

2023-07-07 14:26 UTC, monstermunchkin commented on lxc/cluster.go
> +	}
```suggestion
	c.clusterSet.flagIsAttribute = if c.flagIsAttribute
```

2023-07-07 14:53 UTC, monstermunchkin requested changes

2023-07-07 14:53 UTC, monstermunchkin commented on lxc/utils.go
> +			return t, nil
```suggestion
			}

			return t, nil
```

2023-07-07 14:53 UTC, monstermunchkin commented on lxc/utils.go
> +		return data, nil
```suggestion
		}

		return data, nil
```

2023-07-11 08:58 UTC, ru-fu commented
Should this be property instead of attribute?
https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/

We only have it explicitly documented for instances, but in the docs, we're trying to be consistent in calling everything under `config` options/configuration options and everything on top level properties.

2023-07-11 09:50 UTC, monstermunchkin commented
> Should this be property instead of attribute? https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/
> 

Yes, we should call it `property`.

2023-07-11 13:38 UTC, ru-fu commented
Thanks!
Can you add a "Configure instance properties" section to https://documentation.ubuntu.com/lxd/en/latest/howto/instances_configure/ and update https://documentation.ubuntu.com/lxd/en/latest/explanation/instance_config/ to link to that section for instance properties?

We should probably also update the other configuration how-tos, but we can do that later if needed.

2023-07-11 13:40 UTC, tomponline requested changes
Please can we have some tests added for this functionality too please.

2023-07-11 14:02 UTC, monstermunchkin requested changes

2023-07-12 12:57 UTC, tomponline requested changes
Please can you use the normal [i18n: Update translation templates](https://github.com/canonical/lxd/commit/d4550f9178d0760e960eb641cff1a1ea67b9ffd6) message style (without typo ;) too) when updating i18n.

2023-07-14 09:57 UTC, tomponline commented
@ru-fu I expect that we should update the docs for this new CLI feature, do you have a preference as to where?

2023-07-14 09:58 UTC, tomponline commented
@ru-fu oh wait you already did in https://github.com/canonical/lxd/pull/11961#issuecomment-1630853254, @gabrielmougard please can you add. thanks.

2023-07-14 10:02 UTC, tomponline requested changes
Please can you split your Go commits by file so its possible to backport the ones that are supported by the LTS.

2023-07-14 10:21 UTC, tomponline commented on lxc/utils.go
> +// stringToTimeHookFunc is a custom decoding hook that converts string values to time.Time using the given layout.
Can you move these functions into called something like utils_properties.go to help organise the utils a bit better.

2023-07-14 10:22 UTC, tomponline commented on lxc/utils.go
> +// setFieldByJsonTag sets the value of a struct field by its JSON tag.
These 3 functions below seem to be good candidates for having some unit tests as they are self-contained, especially as they are dealing with different data types using reflect.

2023-07-14 11:59 UTC, tomponline commented
@gabrielmougard looks like this needs a rebase now.

2023-07-17 09:18 UTC, tomponline requested changes
As discussed lets add a test for setting/getting the instance snapshot and storage volume snapshot expiry times.

2023-07-17 13:00 UTC, ru-fu requested changes

2023-07-17 15:39 UTC, tomponline commented on test/suites/config.sh
> +  lxd_backend=$(storage_backend "$LXD_DIR")
I think a default pool for the active storage driver is created by default for all tests, so I dont see why we need to create one here.

2023-07-18 09:09 UTC, gabrielmougard commented on doc/howto/instances_configure.md
> +    lxc config set <instance_name> <option_key>=<option_value> <option_key>=<option_value> ... --property
Then the command will output an error saying that the `<option_key>` has not been found

2023-07-18 09:58 UTC, ru-fu approved these changes
Docs look good.

2023-07-18 10:00 UTC, ru-fu commented on doc/howto/instances_configure.md
> +    lxc config set <instance_name> <option_key>=<option_value> <option_key>=<option_value> ... --property
> Then the command will output an error saying that the `<option_key>` has not been found

How much effort would it be to check if the key exists as an option, and in that case report that back to the user?

We're making a difference between properties and options in the docs, but we cannot necessarily expect users to be aware of the difference. And I could imagine users getting quite confused if we're telling them that one of the keys, which they have used before, suddenly can't be found anymore.

2023-07-18 12:35 UTC, tomponline commented
static analysis failing

2023-07-18 12:36 UTC, tomponline commented on test/suites/config.sh
> +  lxc delete foo
lets use `-f` here for consistency

2023-07-18 14:18 UTC, merged