shared/cmd: Use SetAutoMergeCells(true) for table|compact table rendering
canonical/lxd pull request #12057
Opened 2023-07-21 06:51 UTC by gabrielmougard

This feature allows us to merge cells in adjacent rows if the fields are identical within the same column. Here is an example:

```
+----------------------+-------------------------------------------+----------+-------+-------------------+
|       USED BY        |                 ADDRESSES                 |   TYPE   |  NAT  | HARDWARE ADDRESS  |
+----------------------+-------------------------------------------+----------+-------+-------------------+
| /1.0/networks/lxdbr0 | 10.6.105.1/24                             | network  | false |                   |
+                      +-------------------------------------------+          +       +-------------------+
|                      | fd42:3cce:990:a1fd::1/64                  |          |       |                   |
+----------------------+-------------------------------------------+----------+       +-------------------+
| /1.0/instances/u1    | fd42:3cce:990:a1fd:216:3eff:fe04:f095/128 | instance |       | 00:16:3e:04:f0:95 |
+                      +-------------------------------------------+          +       +                   +
|                      | 10.6.105.160/32                           |          |       |                   |
+----------------------+-------------------------------------------+----------+-------+-------------------+
```

2023-07-21 06:59 UTC, roosterfish approved these changes
Not sure if it breaks some workflows if users don't make use of `-f` for formatting but instead grep from this output?

But I like it, it's nifty.

2023-07-21 07:06 UTC, monstermunchkin requested changes
I'm not opposed to this change, but the tests need to be fixed.

2023-07-21 07:08 UTC, monstermunchkin commented
@gabrielmougard I wouldn't add this to the `compact` mode though, as that will lead to confusion.

2023-07-21 07:09 UTC, gabrielmougard commented
For a bit of context, I thought about introducing this "cell merge" behaviour because of this https://github.com/canonical/lxd/pull/12055

2023-07-21 08:21 UTC, monstermunchkin commented
> In this PR, there is multiple IP addresses per data row (not only one ipv4 and one ipv6 but maybe multiple ipv4 and ipv6). How would you tackle this problem ?

When listing instances with multiple IP addresses, those are just listed underneath each other:
```
$ lxc ls
+---------------------------+---------+------------------------+-----------------------------------------------+-----------------+-----------+
|           NAME            |  STATE  |          IPV4          |                     IPV6                      |      TYPE       | SNAPSHOTS |
+---------------------------+---------+------------------------+-----------------------------------------------+-----------------+-----------+
| node-1                    | RUNNING | 192.168.122.1 (virbr0) | fd42:fa32:2221:1eae:216:3eff:feed:d51a (eth0) | CONTAINER       | 0         |
|                           |         | 10.221.91.11 (eth0)    |                                               |                 |           |
+---------------------------+---------+------------------------+-----------------------------------------------+-----------------+-----------+
```

I'd do the same in this case.

2023-08-15 07:12 UTC, tomponline commented
Can we close this for now?

2023-08-16 07:33 UTC, closed without merging