Add device parameter for importing instance command
canonical/lxd pull request #12144
Opened 2023-08-11 06:05 UTC by Shu-Duan

issue:  [#12000](https://github.com/canonical/lxd/issues/12000)

2023-09-06 08:37 UTC, tomponline commented
Hi @Shu-Duan please can you update the PR description to explain what you are changing here protocol-wise in order to accommodate this functionality?

It will aid with the review.

Thanks

2023-09-12 09:45 UTC, tomponline requested changes
Please can you add an API extension for this change too.

Similar to https://github.com/canonical/lxd/commit/0cf863d03dd560ef29845c6e13e6672ca9177b28

2023-09-20 08:29 UTC, tomponline commented
Moving to draft status

2024-01-18 16:43 UTC, tomponline commented
@Shu-Duan please can you rebase this so we can check if you have signed the Canonical CLA as this is now required. Thanks

2024-01-24 03:30 UTC, Shu-Duan commented
Ok, I would handle it soon.

2024-01-24 09:03 UTC, tomponline commented
> Ok, I would handle it soon.

Excellent thanks!

2024-02-09 06:16 UTC, Shu-Duan commented
Hi, I've added description and docs.
Thx.

2024-02-09 08:41 UTC, tomponline commented
Looks like the CLA hasn't been signed yet im afraid.

https://ubuntu.com/legal/contributors/agreement

2024-02-09 13:00 UTC, Shu-Duan commented
Sorry, I've just signed the CLA.

2024-02-13 10:24 UTC, tomponline commented
Hrm, the CLA check is still failing, ive re-run it:

```
Checking the following users on GitHub:
- qnap-ericfan ✕ (issue checking CLA status [HttpError: User does not exist or is not a member of the organization])

Checking the following users on Launchpad:
- ericfan@qnap.com ✕ (has no Launchpad account)
```

Did you sign it using the user `qnap-ericfan`?

Sorry about this. Also it needs a rebase now.

2024-02-13 10:25 UTC, tomponline commented
@simondeziel please can you have a look and check the CLA checker is working correctly? Thanks

2024-02-13 13:55 UTC, simondeziel commented
https://launchpad.net/~contributor-agreement-canonical/+members shows the last member joined on 2024-01-29 so maybe there is a long delay or if you signed the non-individual version it's longer? @Shu-Duan did you sign individual contributor license or the org one?

2024-02-14 17:47 UTC, simondeziel commented
@Shu-Duan it seems like it did the trick, thanks!

```
Checking the following users on GitHub:
- qnap-ericfan ✓ (has signed the CLA)
```

2024-02-15 05:29 UTC, tomponline commented
Please can you rebase again to get latest changes so static analysis can pass

2024-02-15 12:43 UTC, Shu-Duan commented
Sure, rebased it already.

2024-02-15 12:54 UTC, tomponline commented
> Sure, rebased it already.

Thanks!

Looks like static analysis checks are failing with:

```
Checking that functional blocks are followed by newlines...
client/lxd_instances.go:601
client/lxd_instances.go:603
lxd/backup/backup_config_utils.go:99
lxd/instances_post.go:835
run-parts: test/lint/newline-after-block.sh exited with return code 1
```

2024-02-15 12:54 UTC, tomponline commented on lxd/instances_post.go
> +		return createFromBackup(s, r, targetProjectName, r.Body, r.Header.Get("X-LXD-pool"), r.Header.Get("X-LXD-name"), deviceMap)
need a new line before this line

2024-02-15 12:55 UTC, tomponline commented on client/lxd_instances.go
> +			devProps.Set(dev, props.Encode())
need a new line before this line

2024-02-15 12:56 UTC, tomponline commented on lxd/backup/backup_config_utils.go
> +	defer f.Close()
need a new line before this line

2024-02-20 12:57 UTC, merged