Skip loop devices from IO stats
canonical/lxd pull request #12208
Opened 2023-09-02 00:30 UTC by simondeziel

2023-09-02 03:57 UTC, simondeziel commented
The test failure seems like an unrelated/random error as the tests are all green in my own repo (https://github.com/simondeziel/lxd/actions/runs/6055206345/job/16435757904). For some reason, I cannot retry the failed one here.

2023-09-04 07:20 UTC, tomponline requested changes
Hi @simondeziel please can you update your PR and the comments in the code with an explanation of *why* these changes are being introduced.

2023-09-05 22:07 UTC, simondeziel commented
@tomponline until Aleksandr digs the root cause of those loop device IO stats, are you OK with just calling them "irrelevant"?

2023-09-06 07:02 UTC, tomponline approved these changes

2023-09-06 07:03 UTC, merged