doc: document the project config options
canonical/lxd pull request #12251
Opened 2023-09-14 11:08 UTC by gabrielmougard

This requires [this](https://github.com/canonical/lxd-sphinx-extensions/pull/22) to be merged first

2023-09-19 12:45 UTC, tomponline commented
@gabrielmougard can you rebase this so tests re-run now youve got the extension merged.

2023-09-25 13:13 UTC, ru-fu commented
@gabrielmougard I just reviewed and pushed a commit with doc updates to your branch. Please check and squash as required.
And please make sure to pull the change before you force-push to your branch. ;)

2023-09-26 07:36 UTC, tomponline commented
@gabrielmougard tests are failing

2023-09-26 11:31 UTC, gabrielmougard commented
@ru-fu I integrated your commit

2023-09-26 12:05 UTC, ru-fu requested changes
Some small changes to the config option links, and some that I only noticed after seeing the changes in context. :)

2023-09-26 12:05 UTC, ru-fu commented on doc/reference/projects.md
> +For example, if you set the project's {config:option}`project-limits:limits.memory` configuration to `50GiB`, the sum of the individual values of all {config:option}`project-limits:limits.memory` con
```suggestion
For example, if you set the project's {config:option}`project-limits:limits.memory` configuration to `50GiB`, the sum of the individual values of all {config:option}`instance-resource-limits:limits.memory` configuration keys defined on the project's instances will be kept under 50 GiB.
```

2023-09-26 12:05 UTC, ru-fu commented on doc/reference/projects.md
> +Similarly, setting the project's {config:option}`project-limits:limits.cpu` configuration key to `100` means that the sum of individual {config:option}`project-limits:limits.cpu` values will be kept
```suggestion
Similarly, setting the project's {config:option}`project-limits:limits.cpu` configuration key to `100` means that the sum of individual {config:option}`instance-resource-limits:limits.cpu` values will be kept below 100.
```

2023-09-26 12:05 UTC, ru-fu commented on doc/reference/projects.md
> +  This means that to use {config:option}`project-limits:limits.cpu` on a project, the {config:option}`project-limits:limits.cpu` configuration of each instance in the project must be set to a number
```suggestion
  This means that to use {config:option}`project-limits:limits.cpu` on a project, the {config:option}`instance-resource-limits:limits.cpu` configuration of each instance in the project must be set to a number of CPUs, not a set or a range of CPUs.
```

2023-09-26 12:05 UTC, ru-fu commented on lxd/api_project.go
> +		//  shortdesc: Which CPUs to use in the project
```suggestion
		//  shortdesc: Maximum number of CPUs to use in the project
```

2023-09-26 12:05 UTC, ru-fu commented on lxd/api_project.go
> +		// Only CPUs that are specified here can be used in the individual {config:option}`instance-resource-limits:limits.cpu` configurations set on the instances of the project.
```suggestion
		// This value is the maximum value for the sum of the individual {config:option}`instance-resource-limits:limits.cpu` configurations set on the instances of the project.
```

2023-09-26 12:05 UTC, ru-fu commented on lxd/api_project.go
> +		// This value is the maximum value for the sum of individual {config:option}`instance-resource-limits:limits.processes` configurations set on the instances of the project.
```suggestion
		// This value is the maximum value for the sum of the individual {config:option}`instance-resource-limits:limits.processes` configurations set on the instances of the project.
```

2023-09-26 12:16 UTC, gabrielmougard commented
@ru-fu updated

2023-09-26 12:33 UTC, ru-fu approved these changes
Thank you!

2023-09-26 12:46 UTC, tomponline commented
@gabrielmougard when you're ready for this to be reviewed and merge please mark as ready to review

2023-09-26 14:09 UTC, tomponline approved these changes

2023-09-26 14:09 UTC, merged