Restrict user.* keys
canonical/lxd pull request #12487
Opened 2023-10-31 08:23 UTC by monstermunchkin

This restricts `user.*` keys to only include letters, digits, and punctuation characters.

Fixes #12308

2023-10-31 13:07 UTC, simondeziel commented on test/suites/config.sh
> +  # Validate user.* keys
For completeness, I'd also add a working example like:
```suggestion
  # Validate user.* keys
  lxc config set user.bar foo
```

2023-10-31 13:21 UTC, simondeziel requested changes
Thanks for the test, for completeness, maybe we could add a working one to be sure the feature works before checking for restrictions applied to it.

2023-11-02 12:51 UTC, simondeziel approved these changes
Thanks!

2023-11-02 19:03 UTC, tomponline approved these changes

2023-11-06 19:33 UTC, merged