Feat/remove shiftfs
canonical/lxd pull request #12516
Opened 2023-11-07 18:14 UTC by gabrielmougard

Removing ShiftFS

2023-11-07 20:17 UTC, simondeziel commented
Should https://documentation.ubuntu.com/lxd/en/latest/reference/instance_options/#instance-security:security.syscalls.intercept.mount.shift be dropped (doc and config key)?

2023-11-08 07:29 UTC, gabrielmougard commented
> Should https://documentation.ubuntu.com/lxd/en/latest/reference/instance_options/#instance-security:security.syscalls.intercept.mount.shift be dropped (doc and config key)?
> 
> Searching our doc also turn up other cases of `shiftfs` that probably need to be updated/replaced.

I don't think so, we still are using it to check whether a mount syscall needs shifting:

```go
func (s *Server) MountSyscallShift(c Instance, path string) idmap.IdmapStorageType {
	if shared.IsTrue(c.ExpandedConfig()["security.syscalls.intercept.mount.shift"]) {
		diskIdmap, err := c.DiskIdmap()
		if err != nil {
			return idmap.IdmapStorageNone
		}

		if diskIdmap == nil {
			return c.IdmappedStorage(path, "none")
		}
	}

	return idmap.IdmapStorageNone
}
```

2023-11-08 07:33 UTC, simondeziel commented
> > Should https://documentation.ubuntu.com/lxd/en/latest/reference/instance_options/#instance-security:security.syscalls.intercept.mount.shift be dropped (doc and config key)?
> > Searching our doc also turn up other cases of `shiftfs` that probably need to be updated/replaced.
> 
> I don't think so, we still are using it to check whether a mount syscall needs shifting:

The help text literally mentions `shiftfs`.

2023-11-08 08:06 UTC, gabrielmougard commented
@simondeziel updated

2023-11-08 10:07 UTC, simondeziel commented
https://canonical-ubuntu-documentation-library--12516.com.readthedocs.build/lxd/en/12516/search/?q=shiftfs&check_keywords=yes&area=default shows 2 hits. For the API page, I think replacing or adding the `idmapped mounts` would make sense for all 3 occurrences of `shiftfs`. **If** `shiftfs` is replaced by only `idmapped mounts`, we should probably drop it from the FAQ page too.

2023-11-08 10:23 UTC, simondeziel submitted a review, later dismissed
LGTM, thanks!

2023-11-22 16:30 UTC, tomponline requested changes
Im not sure we should be removing test_container_devices_disk_shift

2023-11-23 14:55 UTC, mihalicyn commented on test/suites/container_devices_disk.sh
> -test_container_devices_disk_shift() {
yes, I think that we need to keep this test and modify a condition `  if ! grep -q shiftfs /proc/filesystems || [ -n "${LXD_SHIFTFS_DISABLE:-}" ]; then` to be something like `  if [ -n "${LXD_IDMAPPED_MOUNTS_DISABLE:-}" ]; then`

2023-11-23 17:42 UTC, gabrielmougard commented
@mihalicyn Can you confirm for the test please?

2023-11-27 08:27 UTC, tomponline commented
@gabrielmougard yes a kernel and distribution with ZFS >= 2.2

2023-11-28 09:02 UTC, tomponline commented
@mihalicyn has an idea on how we can detect if the pool supports idmapped mounts he will let you know.

2023-12-05 10:05 UTC, tomponline approved these changes

2023-12-05 10:06 UTC, merged