lxd/instance/drivers/qemu: Consistently use unix timestamp when comparing snapshots
canonical/lxd pull request #12708
Opened 2024-01-08 12:19 UTC by roosterfish

When syncing VMs to a remote LXD the source and target snapshots creation times get compared. If the times don't match, the snapshot gets retransmitted.

In https://github.com/canonical/lxd/issues/12668 we found that refreshing an instance and switching between using a remote/no remote is causing retransmission of all the instances snapshots:

```bash
lxc init ubuntu:jammy v1 --vm && lxc snapshot v1 && lxc snapshot v1
lxc cp v1 v2 --refresh
lxc cp v1 remote:v2 --refresh # will refresh snap0, snap1 and v1 and set the non unix timestamp as creation date
lxc cp v1 remote:v2 --refresh # refreshes only v1
lxc cp v1 v2 --refresh # will refresh snap0, snap1 and v1 and set the unix timestamp as creation date
lxc cp v1 v2 --refresh # refreshes only v1
```

This change ensures that the unix timestamp is always used so that a user can switch between using a remote/no remote without having to retransmit the snapshots.

2024-01-08 12:31 UTC, MusicDin requested changes
I assume this also needs to be fixed for lxc driver?

https://github.com/canonical/lxd/blob/97792f744ecfd0778f6b9a604e22a2fe01133f7d/lxd/instance/drivers/driver_lxc.go#L5887-L5890

2024-01-08 13:28 UTC, roosterfish commented
@MusicDin thanks Din, that was indeed missing. Fixed now.

2024-01-08 14:13 UTC, MusicDin approved these changes

2024-01-18 09:12 UTC, tomponline commented
@roosterfish im not sure about this, why do we need to remove the sub-second granularity for comparison?

2024-01-18 09:13 UTC, tomponline commented
@roosterfish is it because its stored with only second granularity in the DB?

2024-01-18 09:29 UTC, roosterfish commented
@tomponline the sub-second granularity was the issue in another PR: https://github.com/canonical/lxd/pull/12715.

In this one when LXD compares the snapshots on the source and target it's using different timezones when comparing the timestamps. This is causing a retransmission of all snapshots when switching from refreshing between remotes (migration) to refreshing between two local copies.

2024-01-18 09:40 UTC, tomponline commented
@roosterfish ok thanks for clarification, the problem I see with this is that as well as converting to UTC you are losing the nanosecond component from the snapshot database records.

I think we need to keep this, otherwise we will reintroduce a bug we closed a while back where snapshots taken in the same second were treated as the same even though they were different.

I'm not clear at this stage why the snapshot comparison using the existing method wasn't working properly, it should account for different timezones because it uses time.Equal() and this says:

> // Equal reports whether t and u represent the same time instant.
> // Two times can be equal even if they are in different locations.
> // For example, 6:00 +0200 and 4:00 UTC are Equal.

2024-01-18 09:50 UTC, roosterfish commented
> @roosterfish ok thanks for clarification, the problem I see with this is that as well as converting to UTC you are losing the nanosecond component from the snapshot database records.
> 
> I think we need to keep this, otherwise we will reintroduce a bug we closed a while back where snapshots taken in the same second were treated as the same even though they were different.
> 
> I'm not clear at this stage why the snapshot comparison using the existing method wasn't working properly, it should account for different timezones because it uses time.Equal() and this says:
> 
> > // Equal reports whether t and u represent the same time instant.
> > // Two times can be equal even if they are in different locations.
> > // For example, 6:00 +0200 and 4:00 UTC are Equal.

Thanks, ok I see the problem. I'll mark this as a draft for now to find a better solution.

2024-01-18 10:11 UTC, tomponline commented
Can I see a record of the instance_snaphots and storage_volume_snapshots tables on source/target to see the issue with the timestamps please?

2024-01-19 14:32 UTC, roosterfish commented
> Can I see a record of the instance_snaphots and storage_volume_snapshots tables on source/target to see the issue with the timestamps please?

You are right the timestamp isn't the root cause here. The offer header includes the timestamp without nanoseconds which then causes this in the DB:

```bash
julian@thinkpad:~$ lxc ls
+------+---------+-------------------------+-------------------------------------------------+-----------------+-----------+
| NAME |  STATE  |          IPV4           |                      IPV6                       |      TYPE       | SNAPSHOTS |
+------+---------+-------------------------+-------------------------------------------------+-----------------+-----------+
| c1   | RUNNING | 10.171.103.239 (eth0)   | fd42:dcc1:fa41:9a1d:216:3eff:fe8a:99e0 (eth0)   | CONTAINER       | 1         |
+------+---------+-------------------------+-------------------------------------------------+-----------------+-----------+
| c2   | STOPPED |                         |                                                 | CONTAINER       | 1         |
+------+---------+-------------------------+-------------------------------------------------+-----------------+-----------+
julian@thinkpad:~$ lxc cp c1 localhost:c2 --refresh
julian@thinkpad:~$ lxd sql global 'select * from instances_snapshots'
+-----+-------------+-------+--------------------------------+----------+-------------+---------------------------+
| id  | instance_id | name  |         creation_date          | stateful | description |        expiry_date        |
+-----+-------------+-------+--------------------------------+----------+-------------+---------------------------+
| 452 | 265         | snap0 | 2024-01-19T10:41:14.364962712Z | 0        |             | 0001-01-01T00:00:00Z      |
| 460 | 266         | snap0 | 2024-01-19T11:41:14+01:00      | 0        |             | 0001-01-01T00:53:28+00:53 |
+-----+-------------+-------+--------------------------------+----------+-------------+---------------------------+

```

Now when refreshing locally:

```bash
julian@thinkpad:~$ lxc cp c1 c2 --refresh
julian@thinkpad:~$ lxd sql global 'select * from instances_snapshots'
+-----+-------------+-------+--------------------------------+----------+-------------+----------------------+
| id  | instance_id | name  |         creation_date          | stateful | description |     expiry_date      |
+-----+-------------+-------+--------------------------------+----------+-------------+----------------------+
| 452 | 265         | snap0 | 2024-01-19T10:41:14.364962712Z | 0        |             | 0001-01-01T00:00:00Z |
| 461 | 266         | snap0 | 2024-01-19T10:41:14.364962712Z | 0        |             | 0001-01-01T00:00:00Z |
+-----+-------------+-------+--------------------------------+----------+-------------+----------------------+
```

2024-01-19 14:36 UTC, tomponline commented
@roosterfish ah is this because the offer header cannot support sub-second granularity?

2024-01-19 14:37 UTC, tomponline commented
We might need to extend the offer header to support proper datetimes.

2024-01-19 14:38 UTC, tomponline commented
@roosterfish can you point me towards the offer header that is the problem?

2024-01-19 14:41 UTC, roosterfish commented
> @roosterfish can you point me towards the offer header that is the problem?

Yes the protocols `Snapshot` struct uses a `*int64` instead of e.g. `time.Time`. It's this one here https://github.com/canonical/lxd/blob/main/lxd/migration/migrate.pb.go#L353

2024-01-19 14:45 UTC, tomponline commented
@roosterfish thanks. I think we added an additional metadata frame sent inside the websocket, I wonder if we can (or do) send that creation date in a more fine grained format we can use for comparison if available.

2024-02-15 09:06 UTC, closed without merging