lxdmetadata: connect a substitution database
canonical/lxd pull request #12776
Opened 2024-01-26 15:24 UTC by gabrielmougard

This fix enables the `lxd-metadata` tool to be able to do simple template rendering operations.

Any `{{(.*?)}}` in a longdesc field will now be rendered with its substitution value, if the inner substitution key is found. Else, this template will not be rendered.

2024-01-26 15:25 UTC, tomponline approved these changes

2024-01-26 15:52 UTC, tomponline requested changes
Please can you fix those static analysis errors, it looks like you're forcefully killing the program rather than returning an error up to main and logging it.

2024-01-26 17:25 UTC, ru-fu submitted a review, later dismissed
Looks good to me, just a suggestion.

2024-01-26 17:51 UTC, gabrielmougard commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
Could you define 'realistic values' ?

2024-01-29 08:05 UTC, ru-fu commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
As I suggested above - not empty, and not starting with a space.

2024-01-29 09:12 UTC, gabrielmougard commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
Updated. This new regex should avoid `{{}}`, `{{blah}}`, `{{ blah}}`, `{{blah }}`

2024-01-29 14:24 UTC, ru-fu commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
But `{{blah}}` is what we want? Why is it still working then?

2024-01-29 14:25 UTC, ru-fu commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
Substitutions will NOT have any surrounding spaces.

2024-01-29 14:55 UTC, gabrielmougard commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
Sorry for the misunderstanding. Now it should avoid the surrounding spaces.

2024-01-29 16:39 UTC, ru-fu commented on lxd/lxd-metadata/lxd_metadata.go
> +	tpl                 = regexp.MustCompile(`{{(.*?)}}`)
Now it doesn't allow any spaces at all in the string, or am I reading the expression wrong?
This is maybe a bit stricter than it needs to be - but it's unlikely we'll ever use something like ``{{two words}}`` (but use ``{{two_words}}`` instead), so it should be okay.

2024-01-29 16:40 UTC, ru-fu approved these changes
Thanks!

2024-01-29 16:54 UTC, tomponline approved these changes

2024-01-29 16:54 UTC, merged