Few improvements to bash completion
canonical/lxd pull request #13169
Opened 2024-03-16 02:33 UTC by simondeziel

The main point is the fixed `lxc storage <TAB>` as well as adding a few missing keys to this completion group.

2024-03-17 13:24 UTC, tomponline requested changes
Please could we drop the first two commits.

I tend to suggest using long form arguments when calling commands programmatically as it avoids the reader needing to know what the short hand flags mean (self documenting). I recommend just using short hand flags when actually typing the command on a shell.

2024-03-18 16:54 UTC, simondeziel commented
Done

2024-03-18 16:57 UTC, tomponline submitted a review, later dismissed
Thanks!

2024-03-19 08:20 UTC, tomponline approved these changes

2024-03-19 08:20 UTC, merged