Add `lxd` group creation to installation process
canonical/lxd pull request #13382
Opened 2024-04-24 19:20 UTC by hamistao

@ru-fu added `lxd` group creation information as discussed.

2024-04-25 08:11 UTC, ru-fu reviewed
Thanks, this looks good!
Some small suggestions.

2024-04-25 08:11 UTC, ru-fu commented on doc/installing.md
> +On Ubuntu images, the `lxd` group is already created and the main user is automatically added to it. The group is also created during installation if you {ref}`installed LXD from the snap<installing-
```suggestion
On Ubuntu images, the `lxd` group already exists and the main user is automatically added to it. The group is also created during installation if you {ref}`installed LXD from the snap<installing-from-package>`. If the `lxd` group is missing on your system (as might be the case if you {ref}`installed LXD from the sources <installing-from-source>`), create it and restart the LXD daemon:
```

2024-04-25 08:11 UTC, ru-fu commented on doc/installing.md
> +No users are added to the group on installation. You can then add trusted users to the group.
```suggestion
No users are added to the group on installation. You must add trusted users to the group so they can use LXD:
```

2024-04-25 08:48 UTC, ru-fu submitted a review, later dismissed
Thank you! :rocket:

2024-04-25 13:52 UTC, simondeziel requested changes

2024-04-25 13:52 UTC, simondeziel commented on doc/installing.md
> +grep -q "^lxd:" /etc/group | grep -q $USER && sudo usermod -aG lxd $USER
```suggestion
getent group lxd >/dev/null || sudo groupadd --system lxd # create the group if needed
getent group lxd | grep -qwF "$USER" || sudo usermod -aG lxd "$USER"
```

2024-04-25 13:52 UTC, simondeziel commented on doc/installing.md
> +grep -q "^lxd:" /etc/group && sudo groupadd lxd
```suggestion
getent group lxd >/dev/null || sudo groupadd --system lxd
```

2024-04-25 13:52 UTC, simondeziel commented on doc/installing.md
> +Anyone added to this group will have full control over LXD.
I think we should probably link to [doc/explanation/security.md](https://documentation.ubuntu.com/lxd/en/latest/explanation/security/#local-access-to-the-lxd-daemon) as being a member of that group is akin to being root.

2024-04-29 08:17 UTC, tomponline commented
@hamistao are you able to make the changes suggested by @simondeziel ?

2024-04-29 09:07 UTC, tomponline commented
@ru-fu should we also include the group instructions in https://documentation.ubuntu.com/lxd/en/latest/tutorial/first_steps/ as we've had a new user follow this who was presumably not on Ubuntu and so got a bit stuck, see https://discourse.ubuntu.com/t/lxd-5-21-1-lts-has-been-released/43823/79

2024-04-29 09:44 UTC, ru-fu commented
> @ru-fu should we also include the group instructions in https://documentation.ubuntu.com/lxd/en/latest/tutorial/first_steps/ as 

Yes, that makes sense! Should be a 4th step in the install section - can you add that @hamistao ?

> we've had a new user follow this who was presumably not on Ubuntu and so got a bit stuck, see https://discourse.ubuntu.com/t/lxd-5-21-1-lts-has-been-released/43823/79

Unrelated comment - for `lxd init`, we're saying this can be run without `sudo` for simple configurations:
https://documentation.ubuntu.com/lxd/en/latest/howto/initialize/
Has that changed?

2024-04-29 09:46 UTC, tomponline commented
> Unrelated comment - for `lxd init`, we're saying this can be run without `sudo` for simple configurations:
> https://documentation.ubuntu.com/lxd/en/latest/howto/initialize/
> Has that changed?

Its probably still fine as long as user is in lxd group.

2024-04-29 14:14 UTC, hamistao commented
@ru-fu @simondeziel @tomponline I have made all requested changes. In the [first steps section](https://documentation.ubuntu.com/lxd/en/latest/tutorial/first_steps/) I only added a command to add a user to the `lxd` group since the group itself is created during snap installation (i.e. step 2 in the stallation process).

2024-04-29 14:42 UTC, tomponline approved these changes

2024-04-29 14:42 UTC, merged

2024-04-29 16:04 UTC, ru-fu reviewed
Thank you! :rocket: