Add lxd-migrate flags for non-interactive usage
canonical/lxd pull request #14041
Opened 2024-09-04 13:15 UTC by MusicDin

Added flags for `lxd-migrate` to allow non-interactive usage.

List of added flags:
```
  -c, --config               Config key/value to apply to the new instance
      --instance-name        Name of the new instance
      --instance-type        Type of the instance to create (container or vm)
      --mount-path           Additional container mount paths
      --network              Network name
      --no-profiles          Create the instance with no profiles applied
      --non-interactive      Prevent further interaction if migration form is incomplete and error out instead
      --profiles             Profiles to apply on the new instance (default [default])
      --project              Project name
      --server               Unix or HTTPS URL of the target server
      --source               Path to the root filesystem for containers, or to the disk, image or partition for virtual machines
      --storage              Storage pool name
      --storage-size         Size of the instance's storage volume
      --token                Authentication token for HTTPS remote
```

Some flag names that should be renamed if neccessary:
- `storage-size` - Used for setting storage volume size of a new instance.
- `server` - Server URL (unix/https)
- `instance-name` - I didn't want to use just `name` to be more precise
- `instance-type` - Similar to `instance-name`, `instance-type` is a bit more precise (but long). In addition, allowed values for instance-type are `container` and `vm`, which differs from the interactive mode, where `1` is used for container and `2` for virtual machine.

TODO:
- Docs
- Tests (will be in LXD-CI)
- Currently, only token is supported in non-interactive mode.

2024-09-11 12:26 UTC, tomponline requested changes
Looking good thanks, just a few small questions/changes.

2024-09-16 11:16 UTC, MusicDin commented on lxd-migrate/main_migrate.go
> +	if c.flagNoProfiles {
Yep. I've added the check before attempting to establish connection with a server.

2024-09-17 11:09 UTC, MusicDin commented
@tomponline Ready for another round of reviews

2024-09-17 14:53 UTC, tomponline approved these changes
LGTM thanks!

2024-09-17 14:54 UTC, tomponline commented
@MusicDin please can you update the lxd-ci tests to *also* test for non-interactive usage. Ta

2024-09-17 14:54 UTC, merged

2024-09-17 15:05 UTC, MusicDin commented
Yes, they are already in place: https://github.com/canonical/lxd-ci/pull/283

Just need to wait for lxd-migrate go package to be updated.

2024-09-17 15:06 UTC, tomponline commented
> Yes, they are already in place: [canonical/lxd-ci#283](https://github.com/canonical/lxd-ci/pull/283)

So efficient, thanks!