Improve `make i18n` to ask to commit on changes if any
canonical/lxd pull request #14118
Opened 2024-09-16 22:50 UTC by simondeziel

This tries to add some basic change detection to `make update-pot`, `make update-po` and the meta target `make i18n` so that they suggest committing changes with a "canned" message.

2024-09-16 22:54 UTC, simondeziel commented
Here's what it looks like to produce the last commit:

```
$ make i18n
(cd / ; go install github.com/snapcore/snapd/i18n/xgettext-go@2.57.1)
xgettext-go -o po/lxd.pot --add-comments-tag=TRANSLATORS: --sort-output --package-name=lxd --msgid-bugs-address=lxd@lists.canonical.com --keyword=i18n.G --keyword-plural=i18n.NG lxc/*.go lxc/*/*.go
if git diff --quiet --ignore-matching-lines='^\s*"POT-Creation-Date: .*\n"' -- po/*.pot; then git checkout -- po/*.pot; fi
if [ -t 0 ] && ! git diff --quiet --ignore-matching-lines='^\s*"POT-Creation-Date: .*\n"' -- po/*.pot; then \
	read -rp "Would you like to commit i18n template changes (Y/n)? " answer; \
		if [ "${answer:-y}" = "y" ] || [ "${answer:-y}" = "Y" ]; then \
			git commit -sm "i18n: Update translation templates." -- po/*.pot; fi; \
fi
set -eu; \
for lang in po/ar po/ber po/bg po/ca po/cs po/de po/el po/eo po/es po/fa po/fi po/fr po/he po/hi po/id po/it po/ja po/ka po/ko po/mr po/nb_NO po/nl po/pa po/pl po/pt_BR po/pt po/ru po/si po/sl po/sr po/sv po/te po/th po/tr po/tzm po/ug po/uk po/zh_Hans po/zh_Hant; do\
    msgmerge --backup=none -U $lang.po po/lxd.pot; \
done; \
if [ -t 0 ] && ! git diff --quiet -- po/*.po; then \
	read -rp "Would you like to commit i18n changes (Y/n)? " answer; \
		if [ "${answer:-y}" = "y" ] || [ "${answer:-y}" = "Y" ]; then \
			git commit -sm "i18n: Update translations." -- po/*.po; fi; \
fi
....................................................................................................................................................................... done.
........................................................................................................................................................................ done.
......................................................................................................................................................................... done.
......................................................................................................................................................................... done.
......................................................................................................................................................................... done.
.......................................................................................................................................................................................... done.
................................................................................................................................................................................................................................. done.
.......................................................................................................................................................................................... done.
..................................................................................................................................................................................... done.
................................................................................................................................................................................... done.
........................................................................................................................................................................................ done.
.......................................................................................................................................................................................... done.
.................................................................................................................................................................................... done.
.......................................................................................................................................................................... done.
...................................................................................................................................................................... done.
.................................................................................................................................................................................... done.
............................................................................................................................................................................. done.
..................................................................................................................................................................................... done.
................................................................................................................................................................................. done.
.................................................................................................................................................................................................... done.
............................................................................................................................................................................................... done.
........................................................................................................................................................................................................................ done.
.............................................................................................................................................................................................. done.
.......................................................................................................................................................................... done.
....................................................................................................................................................................................... done.
...................................................................................................................................................................................... done.
.................................................................................................................................................................................................................................................... done.
................................................................................................................................................................................... done.
................................................................................................................................................................................ done.
............................................................................................................................................................................... done.
................................................................................................................................................................................. done.
................................................................................................................................................................................. done.
............................................................................................................................................................................................................. done.
.................................................................................................................................................................................... done.
........................................................................................................................................ [...]

2024-09-17 07:25 UTC, tomponline reviewed
I believe we run this in the CI to check for missing commits, will this block on stdin in those cases?

2024-09-30 09:23 UTC, tomponline requested changes
I believe we run this in the CI to check for missing commits, will this block on stdin in those cases?

2024-09-30 17:40 UTC, simondeziel commented
The `make i18n` check done in `test/lint/i18n-up-to-date.sh` behaves correctly when stdin is closed:

```
$ test/lint/i18n-up-to-date.sh </dev/null
Checking that the .pot files are up to date...
................................................................................................................................................................................. done.
...
```
It doesn't prompt for making any commit.

2024-10-01 09:10 UTC, tomponline approved these changes

2024-10-01 09:10 UTC, merged