Update first_steps.md
canonical/lxd pull request #14152
Opened 2024-09-24 06:09 UTC by Alwoch

The current documentation seems to imply that we are updating snap. I just had to specify that its the lxd snap we're updating to avoid confusion

2024-09-24 16:30 UTC, MggMuggins requested changes
One nit :)

2024-09-24 16:30 UTC, MggMuggins commented on doc/tutorial/first_steps.md
> +   If you get an error message that the lxd snap is already installed, run the following command to refresh it and ensure that you are running an up-to-date version:
Looks like capital "LXD" is the convention here

2024-09-24 16:32 UTC, MggMuggins commented
Also can you please sign [Canonical's CLA](https://ubuntu.com/legal/contributors)?

2024-09-25 09:47 UTC, Alwoch commented
> Also can you please sign [Canonical's CLA](https://ubuntu.com/legal/contributors)?

Done! also I've it to conform to the convention

2024-09-25 14:25 UTC, MggMuggins commented
Thanks; can you also rebase the PR into one commit and use the commit title convention that's described [here](https://documentation.ubuntu.com/lxd/en/latest/contributing/#commit-structure)?

2024-10-03 21:32 UTC, simondeziel commented
`git rebase -i main` should be all you need to then mark the last commit (`capitalize LXD`) for `fixup`. This will "merge" or "fuse" the 2 commits into one.

After that, you should be able to push with force: `git push -f`

2024-10-22 11:31 UTC, tomponline commented
Hi @minaelee please could you assist with either getting this contribution ready to be merged, or potentially make the change yourself and we can close this? Thanks

2024-10-31 13:59 UTC, minaelee commented
@Alwoch Thanks for your contribution! I see that it's your first contribution to Canonical, and I'd love to help you get it ready for merge.

Here are detailed instructions to rebase as well as to update the commit message:
- In a terminal, in a local clone of your fork of the lxd repository, switch to your PR branch (`patch-1`). (Note: if you used the GH web interface to make your commits and PR instead of a local clone, you'll need to clone your forked repository locally, checkout/switch to the PR branch there (`git switch -c patch-1 origin/patch-1`), then sync with `git pull origin patch-1` before you rebase.)
- Then run `git rebase -i main` in your terminal. This will open the text editor set for git, or the default system editor if one isn't set for git.
- In the text editor, you should see a list of your recent commits. To the left of the last commit, change the text `pick` to `fixup`. Save & exit the editor.
- Run `git commit --amend`. This will open the editor again. In it, edit your commit message to something like `doc/tutorial: specify LXD snap` and save & exit.
- Force push the changes with `git push -f`. 

Reach out if you have questions. In the interest of completing this change, I will wait a week and if I haven't heard back, I will close this PR and open a new one with attribution to you.

2024-10-31 14:11 UTC, Alwoch commented
> @Alwoch Thanks for your contribution! I see that it's your first contribution to Canonical, and I'd love to help you get it ready for merge.
> 
> Here are detailed instructions to rebase as well as to update the commit message:
> 
> * In a terminal, in a local clone of your fork of the lxd repository, switch to your PR branch (`patch-1`). (Note: if you used the GH web interface to make your commits and PR instead of a local clone, you'll need to clone your forked repository locally, checkout/switch to the PR branch there (`git switch -c patch-1 origin/patch-1`), then sync with `git pull origin patch-1` before you rebase.)
> * Then run `git rebase -i main` in your terminal. This will open the text editor set for git, or the default system editor if one isn't set for git.
> * In the text editor, you should see a list of your recent commits. To the left of the last commit, change the text `pick` to `fixup`. Save & exit the editor.
> * Run `git commit --amend`. This will open the editor again. In it, edit your commit message to something like `doc/tutorial: specify LXD snap` and save & exit.
> * Force push the changes with `git push -f`.
> 
> Reach out if you have questions. In the interest of completing this change, I will wait a week and if I haven't heard back, I will close this PR and open a new one with attribution to you.

Hi @minaelee , you can go ahead and open a new PR because I'm avoiding cloning the repository.  Thanks

2024-11-04 14:43 UTC, minaelee commented
Closing in favor of #14382; thanks @Alwoch!

2024-11-04 14:43 UTC, closed without merging