db: Print last dqlite entry
canonical/lxd pull request #14378
Opened 2024-10-30 20:27 UTC by MggMuggins

The Dqlite LTS provides a new API [`ReadLastEntryInfo`](https://pkg.go.dev/github.com/canonical/go-dqlite/v2#ReadLastEntryInfo) to provide the raft term and index of a dqlite db on disk. This allows us to be more precise with the definition of "most up-to-date cluster member" in the recovery docs.

2024-10-31 11:31 UTC, minaelee requested changes
- there is a section on MicroCloud at the bottom of the same page that seems more sensible to link to
- "up-to-date" when modifying a noun (as in "I saw the up-to-date report.") and "up to date" otherwise (as in "The report is up to date.")

2024-10-31 11:31 UTC, minaelee commented on doc/howto/cluster_form.md
> +To quickly and automatically set up a basic LXD cluster, you can use [MicroCloud](https://canonical.com/microcloud).
```suggestion
To quickly and automatically set up a basic LXD cluster, you can use {ref}`MicroCloud <use-microcloud>`.
```

2024-10-31 11:31 UTC, minaelee commented on doc/howto/cluster_recover.md
> +To determine which database member is most up-to-date:
```suggestion
To determine which database member is most up to date:
```

2024-10-31 11:31 UTC, minaelee commented on doc/howto/cluster_recover.md
> +- If two members have different terms, the member with the higher term is more up-to-date.
```suggestion
- If two members have different terms, the member with the higher term is more up to date.
```

2024-10-31 11:31 UTC, minaelee commented on doc/howto/cluster_recover.md
> +- If two members have the same term, the member with the higher index is more up-to-date.
```suggestion
- If two members have the same term, the member with the higher index is more up to date.
```

2024-10-31 22:21 UTC, MggMuggins commented
Agreed, thanks!

2024-11-01 13:03 UTC, minaelee approved these changes

2024-11-05 09:59 UTC, tomponline approved these changes

2024-11-05 09:59 UTC, tomponline commented
Thanks!

2024-11-05 09:59 UTC, merged