Safer path operations
canonical/lxd pull request #14490
Opened 2024-11-18 19:38 UTC by simondeziel

2024-11-18 22:52 UTC, kadinsayani approved these changes

2024-11-19 11:27 UTC, tomponline requested changes
To avoid the duplication, and to help with unit tests etc, can this logic be moved into a function like `FilePathSafeJoin(prefix string, items ...string)` or similar which can then be called from each function instead of `filepath.Join`?

2024-11-19 11:34 UTC, tomponline requested changes
Also this change only protects against a particular class of errors, but really we should *also* be checking the input is valid higher up the call chain where we know the context of the input (e.g. its an instance name).

So for instance log file delete for example, there's

```go
err = os.Remove(shared.LogPath(project.Instance(projectName, name), file))
```

But `name` should be replaced with `inst.Name()`, because we are already loading the instance from the DB using the `name` input, so that is itself de-coupling the raw input from the validated input.

Going further, there is also `inst.LogPath()` which does this for you. :)

We could also update `validLogFileName` to return the validated file name, in order to de-couple the raw input `file` from the file name passed to `os.Remove`.

2024-12-09 08:49 UTC, tomponline commented
@simondeziel can we close this for now until you get chance to look at this again?

2024-12-09 13:57 UTC, closed without merging