Misc fixes
canonical/lxd pull request #14714
Opened 2024-12-20 22:42 UTC by simondeziel

2024-12-22 18:36 UTC, tomponline commented on lxd/db/instances.go
> +		q.WriteString(fmt.Sprint(instanceID))
strconv.Itoa maybe better here?

2025-01-05 23:36 UTC, minaelee commented on doc/instance-exec.md
> +  See [`GET /1.0/instances/{name}/logs/exec-output`](swagger:/instances/instance_exec-output_get), [`GET /1.0/instances/{name}/logs/exec-output/{filename}`](swagger:/instances/instance_exec-output_ge
Changing `instance_exec-outputs_get` to `instance_exec-output_get` would result in a broken link, since the `operationId` is still `instance_exec-outputs_get` in `rest-api.yaml` - see [line 10910 in that file](https://github.com/canonical/lxd/blob/393216c4d66c0a65969c65fa8b0bd372b985b56f/doc/rest-api.yaml#L10910).

I tried to confirm this by testing in the RTD preview. The link was broken. However, I realized after further testing that ALL links written using `swagger:` are non-functioning in the RTD preview (either an RTD issue or an issue with the Swagger plugin), so that doesn't help to prove that this PR breaks the link. 

Instead, you can see that if you go to the API from the RTD preview via the sidebar nav instead of from the `swagger:` link and look for the specific endpoint, it's found at: https://canonical-ubuntu-documentation-library--14714.com.readthedocs.build/lxd/en/14714/api/#/instances/instance_exec-outputs_get <-- see that it says **`outputs_get`**

Thus, you will need to update the operationId in rest-api.yaml!

2025-01-07 11:04 UTC, tomponline commented on lxd/db/instances.go
> +	instanceName, snapshotName, _ := strings.Cut(name, shared.SnapshotDelimiter)
This has subtly changed behaviour?

Previously passing `foo/` as `name` would have caused the first if statement part to be run, using "" as the snapshot name.  Which I think would have then returned a not found error as no snapshot named "" exists.

But now using `foo/` will return an empty snapshotName, and the new logic will then use the else block with the instance name, which would find the "foo" instance potentially.

Instead, how about we use the third return value from strings.Cut as the condition for the if statement?

2025-01-07 11:04 UTC, tomponline commented on lxc/completion.go
>  	var remote string
no need for this line now.

2025-01-07 11:12 UTC, tomponline commented on lxd/instances_post.go
> +			rootDevName = fmt.Sprint("root", i)
maybe "root" + strconv.ItoA(i)`?

2025-01-07 11:17 UTC, tomponline requested changes
Looks good, just some minor changes.

2025-01-09 09:10 UTC, tomponline approved these changes

2025-01-09 09:10 UTC, merged