CLI: `lxc network forward` completion improvements
canonical/lxd pull request #14713
Opened 2024-12-20 21:49 UTC by kadinsayani

Closes https://github.com/canonical/lxd/issues/14697.

Summary of changes:
- Fixes `cmpNetworkLoadBalancers`. `cmpNetworkLoadBalancers` should return load balancer addresses, not
network forward addresses.
- Adds `cmpNetworkForwardPortTargetAddresses` to provide target address completions for `lxc network forward port add`.
- Adds network completions to `lxc network forward` create.

2025-01-06 18:46 UTC, simondeziel commented on lxc/completion.go
> +					listenAddressIsIP4 := net.ParseIP(listenAddress).To4() != nil
This `net.ParseIP` could be moved out of the 3 `for` loops, I think.

2025-01-06 19:08 UTC, kadinsayani commented on lxc/completion.go
> +					listenAddressIsIP4 := net.ParseIP(listenAddress).To4() != nil
Thanks, nice catch!

2025-01-06 20:39 UTC, kadinsayani commented on lxc/completion.go
> +				results = make([]string, 0, len(network.Addresses))
We want to include this `make()` to pre-allocate `results` with a capacity equal to the length of `network.Addresses`.

2025-01-08 18:42 UTC, simondeziel approved these changes

2025-01-09 08:38 UTC, roosterfish approved these changes
Looks good to me!

2025-01-09 09:10 UTC, tomponline approved these changes

2025-01-09 09:11 UTC, tomponline commented
needs a rebase plase

2025-01-09 09:11 UTC, tomponline requested changes
please rebase

2025-01-09 14:11 UTC, kadinsayani commented
> please rebase

Rebased ✅

2025-01-10 11:03 UTC, tomponline commented
@kadinsayani sorry please can you rebase again to get the doc fix.

2025-01-10 14:11 UTC, kadinsayani commented
> @kadinsayani sorry please can you rebase again to get the doc fix.

Rebased ✅

2025-01-10 16:47 UTC, tomponline approved these changes

2025-01-10 16:48 UTC, merged